### ISSUE TITLE
Unexported `Big-Float`?

### ISSUE THREAD

**Issue by fosskers** [coalton-lang/coalton#803] opened 2023-01-19 07:25 UTC
The type `Big-Float` is listed as have two typeclass instances, `Transfinite` and `Eq`, but the type itself is not listed in the docs.

![transfinite](https://user-images.githubusercontent.com/229679/213380442-c65829cf-ef97-48a5-91e0-44ceecc21ef5.png)

Clicking the link to `Big-Float` there doesn't do anything. Is this by design?

**Comment by stylewarning** [comment] 2023-01-19 18:48
This is a known "bug" that BIG-FLOAT isn't being added to the docs because it's a part of a separate system: `#:coalton/library/big-float`

This needs to be loaded as an ASDF dependency before they can be used. https://github.com/coalton-lang/coalton/tree/main/library/big-float

**Comment by eliaslfox** [comment] 2023-01-19 21:54
Closing as duplicate of #722

**Closed by eliaslfox** 2023-01-19 21:54 UTC
